services:
  - type: web
    name: food-donation-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - fromGroup: your-env-group-name
